/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import draco from '../../3d/draco.glb'

export type GLTFResult = GLTF & {
  nodes: {
    Untitled078: THREE.Mesh
    Untitled078_1: THREE.Mesh
    Untitled078_2: THREE.Mesh
    Untitled018: THREE.Mesh
    Untitled018_1: THREE.Mesh
    Untitled018_2: THREE.Mesh
    Untitled064: THREE.Mesh
    Untitled064_1: THREE.Mesh
    Untitled064_2: THREE.Mesh
    Untitled064_3: THREE.Mesh
    Untitled052: THREE.Mesh
    Untitled052_1: THREE.Mesh
    Untitled052_2: THREE.Mesh
    Untitled072: THREE.Mesh
    Untitled072_1: THREE.Mesh
    Untitled072_2: THREE.Mesh
    Untitled007: THREE.Mesh
    Untitled007_1: THREE.Mesh
    Untitled007_2: THREE.Mesh
    aesop_GLBC001: THREE.Mesh
  }
  materials: {
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
    ['default']: THREE.MeshStandardMaterial
  }
}

export default function Model ({ ...props }: JSX.IntrinsicElements['group']): React.ReactElement {
  const group = useRef<THREE.Group>()
  const { nodes } = useGLTF(draco) as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.42, 0, -1.93]} rotation={[Math.PI / 2, 0, 2.99]} scale={[0.01, 0.01, 0.01]}>
        <mesh geometry={nodes.Untitled078.geometry} material={nodes.Untitled078.material} />
        <mesh geometry={nodes.Untitled078_1.geometry} material={nodes.Untitled078_1.material} />
        <mesh geometry={nodes.Untitled078_2.geometry} material={nodes.Untitled078_2.material} />
      </group>
      <group position={[0.91, 0, -1.91]} rotation={[Math.PI / 2, 0, 3.11]} scale={[0.01, 0.01, 0.01]}>
        <mesh geometry={nodes.Untitled018.geometry} material={nodes.Untitled018.material} />
        <mesh geometry={nodes.Untitled018_1.geometry} material={nodes.Untitled018_1.material} />
        <mesh geometry={nodes.Untitled018_2.geometry} material={nodes.Untitled018_2.material} />
      </group>
      <group position={[-0.18, 0, -1.81]} rotation={[Math.PI / 2, 0, 2.88]} scale={[0.01, 0.01, 0.01]}>
        <mesh geometry={nodes.Untitled064.geometry} material={nodes.Untitled064.material} />
        <mesh geometry={nodes.Untitled064_1.geometry} material={nodes.Untitled064_1.material} />
        <mesh geometry={nodes.Untitled064_2.geometry} material={nodes.Untitled064_2.material} />
        <mesh geometry={nodes.Untitled064_3.geometry} material={nodes.Untitled064_3.material} />
      </group>
      <group position={[-0.81, 0, -1.93]} rotation={[Math.PI / 2, 0, 2.96]} scale={[0.01, 0.01, 0.01]}>
        <mesh geometry={nodes.Untitled052.geometry} material={nodes.Untitled052.material} />
        <mesh geometry={nodes.Untitled052_1.geometry} material={nodes.Untitled052_1.material} />
        <mesh geometry={nodes.Untitled052_2.geometry} material={nodes.Untitled052_2.material} />
      </group>
      <group position={[-1.21, 0, -1.9]} rotation={[Math.PI / 2, 0, -1.1]} scale={[0.01, 0.01, 0.01]}>
        <mesh geometry={nodes.Untitled072.geometry} material={nodes.Untitled072.material} />
        <mesh geometry={nodes.Untitled072_1.geometry} material={nodes.Untitled072_1.material} />
        <mesh geometry={nodes.Untitled072_2.geometry} material={nodes.Untitled072_2.material} />
      </group>
      <group position={[-1.52, 0, -1.9]} rotation={[Math.PI / 2, 0, 2.72]} scale={[0.01, 0.01, 0.01]}>
        <mesh geometry={nodes.Untitled007.geometry} material={nodes.Untitled007.material} />
        <mesh geometry={nodes.Untitled007_1.geometry} material={nodes.Untitled007_1.material} />
        <mesh geometry={nodes.Untitled007_2.geometry} material={nodes.Untitled007_2.material} />
      </group>
      <mesh
        geometry={nodes.aesop_GLBC001.geometry}
        material={nodes.aesop_GLBC001.material}
        rotation={[Math.PI / 2, 0, 2.88]}
        scale={[0.01, 0.01, 0.01]}
      />
    </group>
  )
}

useGLTF.preload(draco)
