/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { ReactElement, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import picnic from '../../3d/picnic.gltf'

type GLTFResult = GLTF & {
  nodes: {
    Box001: THREE.Mesh
  }
  materials: {
    _16451_Picnic_table_default: THREE.MeshStandardMaterial
  }
}

export default function Model ({ ...props }: JSX.IntrinsicElements['group']): ReactElement {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(picnic) as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Box001.geometry} material={materials._16451_Picnic_table_default}>
        {props.children}
      </mesh>
    </group>
  )
}

useGLTF.preload(picnic)
